#!/bin/bash

USER_NICKNAME=""
USER_NUMBER=""
USER_STATE=""


declare -a GROUPS_LIST
declare -a FRIENDS_LIST_RAW
declare -a FRIENDS_NICK_LIST
declare -a FRIENDS_MARK_LIST
declare -a FRIENDS_GROUP_LIST
GROUPS_COUNT=0
FRIENDS_COUNT=0